# Generated by Django 4.2.5 on 2023-09-26 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Designação',
            new_name='Designacoe',
        ),
    ]
